FROM eclipse-temurin:25
RUN groupadd -r psring && useradd -r -g spring spring
USER spring:spring
ARG JAR_FILE=build/libs/*SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT [ "java", "-jar", "/app.jar" ]
