#Postgres
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.offset.storage.file.filename=/data/offsets.dat
debezium.source.database.hostname=users-database
debezium.source.database.port=5432
debezium.source.database.user=usuario
debezium.source.database.password=admin
debezium.source.database.dbname=users_database
debezium.source.plugin.name=pgoutput

#RabbitMQ
debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=usuario
debezium.sink.rabbitmq.connection.password=admin
debezium.sink.rabbitmq.exchange=debezium.exchange
debezium.sink.rabbitmq.exchange.type=topic
debezium.source.topic.prefix=cdc

#Format
debezium.format.key=json
debezium.format.value=json

quarkus.log.console.json=false
debezium.source.snapshot.mode: when_needed
