spring.application.name=authService

spring.mongodb.host=auth-database
spring.mongodb.port=27017

spring.mongodb.database=auth_database
spring.mongodb.username=usuario
spring.mongodb.password=admin
spring.mongodb.authentication-database=admin

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=usuario
spring.rabbitmq.password=admin
