spring.application.name=authService

spring.data.mongodb.host=auth-database
spring.data.mongodb.port=27017

spring.data.mongodb.database=auth_database
spring.data.mongodb.username=usuario
spring.data.mongodb.password=admin

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=usuario
spring.rabbitmq.password=admin
