spring.config.import=optional:file:src/main/resources/application-secrets.properties

spring.application.name=mailService
server.port=${PORT:8080}

spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=${MAILJET_API_KEY}
spring.mail.password=${MAILJET_SECRET_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=in-v3.mailjet.com
app.mail.from=manutencaoequipamentos3@gmail.com
spring.mail.properties.mail.debug=true


spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=usuario
spring.rabbitmq.password=admin