services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" #porta para o webapp de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: usuario
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  users-database:
    image: postgres
    container_name: users-database
    ports:
      - "1501:5432"

    environment:
      POSTGRES_DB: users_database
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data

    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway-service-node:
    build:
      context: ..
      dockerfile: docker/node-build.dockerfile
      args:
        PROJECT_DIR: apiGatewayServiceNode
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - EMAIL_SERVICE_URL=http://email-service:3005

  email-service:
    build:
      context: ..
      dockerfile: docker/email-service.dockerfile
      args:
        PROJECT_DIR: emailService
    depends_on:
      - rabbitmq
    ports:
      - "3006:3005"
    environment:
      - PORT=3005

  users-service:
    build:
      context: ..
      dockerfile: docker/spring-boot-service.dockerfile
      args:
        PROJECT_DIR: usersService
    restart: always
    volumes:
      - gradle-caches:/home/gradle/.gradle/caches
      - gradle-wrapper:/home/gradle/.gradle/wrapper
    depends_on:
      rabbitmq:
        condition: service_healthy
      users-database:
        condition: service_started
    ports:
      - "8082:8080"
    environment:
      - GRADLE_OPTS=-Xmx512m -Xms256m -XX:+HeapDumpOnOutOfMemoryError

  contas-service:
    build:
      context: ..
      dockerfile: docker/spring-boot-service.dockerfile
      args:
        PROJECT_DIR: contasService
    restart: always
    volumes:
      - gradle-caches:/home/gradle/.gradle/caches
      - gradle-wrapper:/home/gradle/.gradle/wrapper
    depends_on:
      users-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8084:8080"
    environment:
      - GRADLE_OPTS=-Xmx512m -Xms256m -XX:+HeapDumpOnOutOfMemoryError

  gerentes-service:
    build:
      context: ..
      dockerfile: docker/spring-boot-service.dockerfile
      args:
        PROJECT_DIR: gerentesService
    restart: always
    volumes:
      - gradle-caches:/home/gradle/.gradle/caches
      - gradle-wrapper:/home/gradle/.gradle/wrapper
    depends_on:
      contas-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      - GRADLE_OPTS=-Xmx512m -Xms256m -XX:+HeapDumpOnOutOfMemoryError

  orchestrator-service:
    build:
      context: ..
      dockerfile: docker/spring-boot-service.dockerfile
      args:
        PROJECT_DIR: orchestratorService
    restart: always
    volumes:
      - gradle-caches:/home/gradle/.gradle/caches
      - gradle-wrapper:/home/gradle/.gradle/wrapper
    depends_on:
      contas-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      - GRADLE_OPTS=-Xmx512m -Xms256m -XX:+HeapDumpOnOutOfMemoryError

volumes:
  pgdata:
  rabbitmq_data:
  gradle-caches:
  gradle-wrapper:
