spring.application.name=contasService

spring.datasource.url=jdbc:postgresql://users-database:5432/users_database?currentSchema=contas_schema
spring.jpa.properties.hibernate.default_schema=contas_schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.datasource.username=usuario
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=usuario
spring.rabbitmq.password=admin
