package br.ufpr.dac.orchestratorService.saga.autocadastroSaga;

import br.ufpr.dac.orchestratorService.saga.sagaStep;

public enum AutocadastroPasso implements sagaStep {
  VALIDANDO_CPF,
  REGISTRANDO_SOLICITACAO,
  ESCOLHENDO_GERENTE,
  VINCULANDO_GERENTE,
  AGUARDANDO_APROVACAO,
  APROVANDO_SOLICITACAO,
  CRIANDO_CONTA,
  CRIANDO_AUTH,
  ENVIANDO_EMAIL_APROVACAO,
  REJEITANDO_SOLICITACAO,
  ENVIANDO_EMAIL_REJEICAO,
  ENVIANDO_EMAIL_FALHA,
  COMPENSANDO_SOLICITACAO,
  COMPENSANDO_CONTA,
  COMPENSANDO_AUTH,
  FINALIZADO
}
